insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("tv", "HomeAppliances", 20, "삼성전자", 200, "Full HD TV")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("washer", "HomeAppliances", 10, "LG전자", 100, "최신형 세탁기")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("shoes", "FashionGoods", 3, "아디다스", 30, "초경량 운동화")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("shirts", "FashionGoods", 1, "자라", 10, "린넨 셔츠")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("aircon", "HomeAppliances", 15, "삼성전자", 30, "최신형 에어컨")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("mouse", "Computer", 2, "삼성전자", 50, "무선 마우스")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("keyboard", "Computer", 2, "삼성전자", 70, "무선 키보드")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("monitor", "Computer", 8, "LG전자", 150, "와이드 모니터")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("laptop", "Computer", 25, "hp", 250, "최신형 노트북")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("desktop", "Computer", 27, "Apple", 1, "최신형 컴퓨터")